name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of the library are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: search-engine
    attributes:
      label: Search Engine
      description: Which search engine(s) are affected?
      multiple: true
      options:
        - Google
        - Bing
        - DuckDuckGo
        - Yahoo
        - Mojeek
        - Brave
        - All
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code to Reproduce
      description: Please provide minimal code to reproduce the issue
      render: python
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any error messages or stack traces
      render: shell

  - type: checkboxes
    id: proxy
    attributes:
      label: Are you using a proxy?
      options:
        - label: Using ScraperAPI
        - label: Using custom proxy
        - label: No proxy (direct connection)
